/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_illuminant_free: (a: number, b: number) => void;
export const illuminant_new_js: (a: number, b: number) => [number, number, number];
export const illuminant_Values: (a: number) => [number, number];
export const illuminant_cri: (a: number) => [number, number, number];
export const illuminant_illuminant: (a: number) => number;
export const __wbg_rgb_free: (a: number, b: number) => void;
export const __wbg_cielab_free: (a: number, b: number) => void;
export const __wbg_viewconditions_free: (a: number, b: number) => void;
export const __wbg_get_viewconditions_dopt: (a: number) => [number, number];
export const __wbg_set_viewconditions_dopt: (a: number, b: number, c: number) => void;
export const __wbg_get_viewconditions_f: (a: number) => number;
export const __wbg_set_viewconditions_f: (a: number, b: number) => void;
export const __wbg_get_viewconditions_la: (a: number) => number;
export const __wbg_set_viewconditions_la: (a: number, b: number) => void;
export const __wbg_get_viewconditions_nc: (a: number) => number;
export const __wbg_set_viewconditions_nc: (a: number, b: number) => void;
export const __wbg_get_viewconditions_yb: (a: number) => number;
export const __wbg_set_viewconditions_yb: (a: number, b: number) => void;
export const __wbg_get_viewconditions_c: (a: number) => number;
export const __wbg_set_viewconditions_c: (a: number, b: number) => void;
export const __wbg_xyz_free: (a: number, b: number) => void;
export const xyz_new_js: (a: number, b: number, c: any) => [number, number, number];
export const xyz_values: (a: number) => any;
export const xyz_chromaticity: (a: number) => any;
export const xyz_luminousValue: (a: number) => number;
export const __wbg_spectrum_free: (a: number, b: number) => void;
export const spectrum_new_js: (a: number, b: number) => [number, number, number];
export const spectrum_Values: (a: number) => [number, number];
export const spectrum_linearInterpolate: (a: number, b: number, c: number, d: number, e: any) => [number, number, number];
export const spectrum_cri: (a: number) => [number, number, number];
export const __wbg_cri_free: (a: number, b: number) => void;
export const __wbg_munsellmatt_free: (a: number, b: number) => void;
export const __wbg_observerdata_free: (a: number, b: number) => void;
export const stefanBoltzmann: (a: number) => number;
export const __wbindgen_export_0: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
